FROM alpine:latest as build

RUN apk update \
    && apk add wget lua5.1-dev git unzip make g++ curl openssl openssl-dev \
    && cd /tmp \
    && git clone https://github.com/keplerproject/luarocks.git --branch v3.9.1 --single-branch --depth=1 \
    && cd luarocks \
    && sh ./configure \
    && make build install \
    && cd / \
    && rm -rf /tmp/luarocks


# install dependencies separately to not have --dev versions for them as well
RUN luarocks install luasec
RUN luarocks install copas
RUN luarocks install lualogging
RUN luarocks install penlight
RUN luarocks install Tieske/luamqtt --dev
RUN luarocks install homie --dev
RUN luarocks install luabitop
RUN luarocks install netatmo --dev

# copy the local repo contents and build it
COPY ./ /tmp/homie-netatmo
RUN cd /tmp/homie-netatmo && luarocks make


FROM  alpine:latest
RUN apk add --no-cache lua5.1 openssl

# copy luarocks tree and data over
COPY --from=build /usr/local/lib/lua /usr/local/lib/lua
COPY --from=build /usr/local/share/lua /usr/local/share/lua
COPY --from=build /usr/local/lib/luarocks /usr/local/lib/luarocks
# copy the command as generated by LuaRocks
COPY --from=build /usr/local/bin/homienetatmo /usr/local/bin/homienetatmo

CMD homienetatmo
